[package]
name = "risp"
version = "0.6.0"
authors = ["shivrm"]
license = "MIT"
edition = "2021"
description = "A LISP-like language"

[dependencies]
lazy_static = "1.4.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
